variable "ami_id" {
  description = "The AMI ID for the EC2 instance."
  type        = string
}

variable "mlflow_db_username" {
  description = "The username for the database"
}

variable "mlflow_db_password" {
  description = "The password for the database"
  sensitive   = true
}

variable "iam_instance_profile" {
  description = "IAM instance profile name"
  type        = string
}


variable "main_subnet" {
  description = ""
}

variable "allow_http" {
  description = ""
}

variable "region" {
  description = "AWS Region"
}

variable "generated_key_name" {
  type        = string
  default     = "ben-mlops"
  description = "Key-pair generated by Terraform"
}